name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.zig"
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - "**.zig"
      - ".github/workflows/**"

jobs:
  examples:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: Run examples(Unix)
        if: matrix.os != 'windows-latest'
        working-directory: examples
        run: zig build run-all --summary all

      - name: Run examples(Windows)
        if: matrix.os == 'windows-latest'
        working-directory: examples
        run: zig.exe build run-all --summary all
